/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package THUCHANHJLIST;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author anhki
 */
public class THUCHANHJLIST extends javax.swing.JFrame {
    DefaultListModel model11;
    DefaultListModel model12;
    public THUCHANHJLIST() {
        initComponents();
        model11=new DefaultListModel();
        model11.addElement("Giái Tích");
        model11.addElement("Tin Học");
        model11.addElement("Vật Lý");
        model11.addElement("Pháp Luật");
        model12=new DefaultListModel();
        listtrai.setModel(model11);
        listphai.setModel(model12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jphai = new javax.swing.JButton();
        jallphai = new javax.swing.JButton();
        jtrai = new javax.swing.JButton();
        jalltrai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listtrai = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listphai = new javax.swing.JList<>();
        jcong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH MÔN HỌC");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("MÔN HỌC ƯA THÍCH");

        jphai.setText("THÊM");
        jphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jphaiActionPerformed(evt);
            }
        });

        jallphai.setText("THÊM TẤT CẢ");
        jallphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jallphaiActionPerformed(evt);
            }
        });

        jtrai.setText("BỎ");
        jtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtraiActionPerformed(evt);
            }
        });

        jalltrai.setText("BỎ TẤT CẢ");
        jalltrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jalltraiActionPerformed(evt);
            }
        });

        listtrai.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listtrai);

        listphai.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listphai);

        jcong.setText("THÊM MÔN HỌC KHÁC");
        jcong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jallphai)
                            .addComponent(jphai, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtrai, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jalltrai, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcong)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addGap(45, 45, 45)
                        .addComponent(jcong)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jphai)
                                .addGap(30, 30, 30)
                                .addComponent(jallphai)
                                .addGap(18, 18, 18)
                                .addComponent(jtrai)
                                .addGap(18, 18, 18)
                                .addComponent(jalltrai))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jphaiActionPerformed
     int[] indexs = listtrai.getSelectedIndices();
        for(int i = indexs.length-1; i>=0;i--)
        {
            model12.addElement(model11.get(indexs[i]));
            model11.remove(indexs[i]);
        }
    }//GEN-LAST:event_jphaiActionPerformed

    private void jtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtraiActionPerformed
       int[] indexs = listphai.getSelectedIndices();
        for(int i = indexs.length-1; i>=0;i--)
        {
            model11.addElement(model12.get(indexs[i]));
            model12.remove(indexs[i]);
        }
    }//GEN-LAST:event_jtraiActionPerformed

    private void jcongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcongActionPerformed
        String sTheThao=JOptionPane.showInputDialog(this,"Danh sách môn học");
        model11.addElement(sTheThao);
    }//GEN-LAST:event_jcongActionPerformed

    private void jallphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jallphaiActionPerformed
         int rt = model11.getSize();
        for(int i = 0; i < rt ; i++)
        {
            model12.addElement(model11.get(i));
        }
        model11.clear();
    }//GEN-LAST:event_jallphaiActionPerformed

    private void jalltraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jalltraiActionPerformed
        int rt = model12.getSize();
        for(int i = 0; i < rt ; i++)
        {
            model11.addElement(model12.get(i));
        }
        model12.clear();
    }//GEN-LAST:event_jalltraiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(THUCHANHJLIST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(THUCHANHJLIST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(THUCHANHJLIST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(THUCHANHJLIST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new THUCHANHJLIST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jallphai;
    private javax.swing.JButton jalltrai;
    private javax.swing.JButton jcong;
    private javax.swing.JButton jphai;
    private javax.swing.JButton jtrai;
    private javax.swing.JList<String> listphai;
    private javax.swing.JList<String> listtrai;
    // End of variables declaration//GEN-END:variables
}
